### ISSUE TITLE
关于 USB-A 封装的问题

### ISSUE THREAD

**Issue by linyuxuanlin** [peng-zhihui/Planck-Pi#14]
![image](https://user-images.githubusercontent.com/13746617/168629326-d255c8ca-66f5-4812-8baf-e04699029c4f.png)

如上图所示，USB-A 座子的模型与封装的两个引脚对应有点偏差，我查到的相似物料，是与图中 3D 模型的尺寸相契合的，是否为 PCB 封装绘制的问题呢？

**Comment by peng-zhihui** [comment]
3D模型的问题，不影响
