### ISSUE TITLE
请问zhihui君有推荐的店铺吗，之前是在哪家店买的？不知道是不是受到芯片涨价的影响，淘宝上搜 F1C200S都八九十了，qwq咸鱼的怕旧的会有故障

### ISSUE THREAD

**Issue by VectorLu** [peng-zhihui/Planck-Pi#2]

**Comment by ZK-y53** [comment]
稚晖君做项目从来都是不计成本的，再说了，你搜的啥店铺？据我了解，年前价格好像是20块钱左右的样子呀。

**Comment by peng-zhihui** [comment]
芯片目前大概20块钱

**Comment by VectorLu** [comment]
> 芯片目前大概20块钱

ohhh，sorry，我看的是成品开发板的价格，我只懂Linux等软件，基本完全不懂硬件，这个项目是要从头自己搭建开发板组装硬件是吧，我先去再学习一下硬件的相关知识；打扰zhihui了，十分抱歉。我学习个硬件设计打板再来。
