### ISSUE TITLE
关于F1C200S第20脚是否应该为3V3

### ISSUE THREAD

**Issue by CWEIB** [peng-zhihui/Planck-Pi#7]
晖哥你好，关于芯片的20号引脚是否应该为3v3，看过芯片的datasheet，应该为3v3，看过芒果派和荔枝派的原理图此脚都是3v3
这是Planck-Pi的原理图
![屏幕截图 2022-04-14 175357](https://user-images.githubusercontent.com/44942392/163361923-e17b5485-9d0a-4891-b7cb-10434dbc3221.png)
这是datasheet中的
![屏幕截图 2022-04-14 175822](https://user-images.githubusercontent.com/44942392/163362069-a9dadb14-a30c-4941-8d18-4739a7c58b22.png)
![屏幕截图 2022-04-14 175948](https://user-images.githubusercontent.com/44942392/163362323-eba315f8-21f9-45c0-bd88-fb95dd713b62.png)
芒果派的原理图
![屏幕截图 2022-04-14 180048](https://user-images.githubusercontent.com/44942392/163362530-33816629-e111-4ee7-9160-44104ca9791b.png)

**Comment by peng-zhihui** [comment]
是的，疏忽了，已修复

**Comment by CWEIB** [comment]
收到，谢谢晖哥回复

**Comment by ansonxu1998** [comment]
请问这个影响使用吗？修改之前已经打板了，是否需要重新打板？

**Comment by CWEIB** [comment]
是的，会影响使用，如果还没焊接元器件建议重新打样，焊接了的话可以挖断20脚的1.2v然后飞线到3v3
