### ISSUE TITLE
图形的BOM表

### ISSUE THREAD

**Issue by yukaichao** [peng-zhihui/Planck-Pi#8]
[Planck-Pi-DK.zip](https://github.com/peng-zhihui/Planck-Pi/files/8530232/Planck-Pi-DK.zip)

**Comment by yukaichao** [comment]
可以添加到硬件目录吗

**Comment by peng-zhihui** [comment]
已添加，感谢

**Comment by yukaichao** [comment]
https://www.xn--w9q392c0zw.cn/PCB/Planck-Pi-DK.html

我放我自己服务器上了，可以直接点链接看了
