### ISSUE TITLE
麻烦问一下，咪头的具体型号，根据封装，在淘宝上并未找到，谢谢！

### ISSUE THREAD

**Issue by tony2ty** [peng-zhihui/Planck-Pi#9]

**Comment by yukaichao** [comment]
【淘宝】https://m.tb.cn/h.frKJkbw?tk=RJi6285gjWS「【优信电子】4013贴片咪头  驻极体话筒 拾音器 麦克风」
点击链接直接打开

**Comment by tony2ty** [comment]
> 【淘宝】[https://m.tb.cn/h.frKJkbw?tk=RJi6285gjWS「【优信电子】4013贴片咪头](https://m.tb.cn/h.frKJkbw?tk=RJi6285gjWS%E3%80%8C%E3%80%90%E4%BC%98%E4%BF%A1%E7%94%B5%E5%AD%90%E3%80%914013%E8%B4%B4%E7%89%87%E5%92%AA%E5%A4%B4) 驻极体话筒 拾音器 麦克风」 点击链接直接打开

谢谢
